global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'fastapi'
    static_configs:
      - targets: ['fastapi:8000']

  - job_name: 'redis'
    static_configs:
      - targets: ['redis_exporter:9121']
